### PR TITLE
Patch VMware Tools

### LINKED ISSUE #7: VMWare boxes for Wheezy 7.8
Would it possible to provide a vmware box for Wheezy 7.8?

### PR DESCRIPTION
**Pull request by rasa**
Fixes #7

### CODE REVIEW

**Comment by rasa** [comment]
This code is untested, so I committed to a branch.

**Comment by annawake** [comment]
Does not work:

```
==> vmware-iso: Provisioning with shell script: script/vmtool.sh
    vmware-iso: ==> Installing VMware Tools
    vmware-iso: Reading package lists... Done
    vmware-iso: Building dependency tree
    vmware-iso: Reading state information... Done
    vmware-iso: build-essential is already the newest version.
    vmware-iso: perl is already the newest version.
    vmware-iso: linux-headers-3.2.0-4-amd64 is already the newest version.
    vmware-iso: 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    vmware-iso: mount: block device /home/vagrant/linux.iso is write-protected, mounting read-only
    vmware-iso: /tmp/script.sh: line 11: git: command not found
    vmware-iso: /tmp/script.sh: line 12: vmware-tools-patches/untar-and-patch.sh: No such file or   directory
    vmware-iso: /tmp/script.sh: line 13: vmware-tools-distrib/vmware-install.pl: No such file or directory
```

**Comment by rasa** [comment]
Lemme test it out locally, first.

**Comment by rasa** [comment]
Compiled fine. See https://gist.github.com/rasa/96f78041dbfced1bfdd4

**Comment by mathewpeterson** [comment]
Awesome! Thanks @rasa!

**Pull request merged**
